{{- if and .Values.global.lion.init .Values.lion.init }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ .Chart.Name }}-lion-init-configmap"
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade,pre-rollback
    "helm.sh/resource-policy": keep
    "helm.sh/hook-weight": "1"
    "helm.sh/hook-delete-policy": before-hook-creation
data:
{{- if .Files.Glob "files/lion/*.{properties}" }}
{{ (.Files.Glob "files/lion/*.{properties}").AsConfig | indent 2 }}
{{- end }}
{{- end }}
